#!/usr/bin/env bun

import { createBlueprint } from "./blueprint";
import {
  addScript,
  createModel,
  renderArtifacts,
  writeText,
} from "./model";
import { resolveCapabilities } from "./resolver";

const blueprint = createBlueprint({
  repoName: "demo-monorepo",
  outputDir: "./demo-monorepo",
});

const resolution = resolveCapabilities(blueprint);
const model = createModel(blueprint);

addScript(model, "build", "turbo run build");
writeText(
  model,
  "README.md",
  `# ${blueprint.repo.name}

Generated by Monofactory.
`,
);

const artifacts = renderArtifacts({
  blueprint,
  resolvedCapabilities: resolution.resolved,
  model,
});

console.log("monofactory bootstrap");
console.log(`resolved: ${resolution.resolved.join(", ")}`);
console.log(`artifacts: ${[...artifacts.keys()].sort().join(", ")}`);