import type { Blueprint, Capability } from "./types";
import {
  addDevDependency,
  addScript,
  writeJson,
  writeText,
  type RepoModel,
} from "./model";
import { capabilityRegistry } from "./resolver";

type ModuleApplyFn = (blueprint: Blueprint, model: RepoModel) => void;

interface ModuleImplementation {
  apply: ModuleApplyFn;
}

const moduleImplementations: Record<Capability, ModuleImplementation> = {
  "repo-core": {
    apply: (blueprint, model) => {
      addScript(model, "dev", "turbo run dev");
      addScript(model, "build", "turbo run build");
      addScript(model, "typecheck", "turbo run typecheck");
      addScript(model, "lint", "turbo run lint");
      addScript(model, "test", "turbo run test");

      writeText(
        model,
        "README.md",
        `# ${blueprint.repo.name}

This repository was generated by Monofactory.

## Topology

- apps/
- packages/
- infra/
- docs/
- governance/
`,
      );

      writeText(
        model,
        ".gitignore",
        `
node_modules
dist
.turbo
coverage
.env
.env.*
bun.lock
`,
      );

      writeText(
        model,
        ".editorconfig",
        `
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
`,
      );

      writeText(model, "apps/README.md", "# Apps\n");
      writeText(model, "packages/README.md", "# Packages\n");
      writeText(model, "docs/README.md", "# Docs\n");
      writeText(model, "infra/README.md", "# Infra\n");
      writeText(model, "governance/README.md", "# Governance\n");

      if (blueprint.policies.requireContributingMd) {
        writeText(
          model,
          "CONTRIBUTING.md",
          `# Contributing

- Prefer explicit changes over hidden behavior.
- Keep generator-driven behavior deterministic.
- Document architectural changes before implementation.
`,
        );
      }

      if (blueprint.policies.requireSecurityMd) {
        writeText(
          model,
          "SECURITY.md",
          `# Security

## Reporting

Please report vulnerabilities privately.

## Current posture

This repository is under active development.
`,
        );
      }

      writeJson(model, "tsconfig.base.json", {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "Bundler",
          strict: true,
          noEmit: true,
          skipLibCheck: true,
          verbatimModuleSyntax: true,
          baseUrl: ".",
          types: ["node"],
          paths: {
            "@workspace/shared": ["packages/shared/src/index.ts"],
          },
        },
      });
    },
  },

  turbo: {
    apply: (_blueprint, model) => {
      addDevDependency(model, "turbo");

      writeJson(model, "turbo.json", {
        $schema: "https://turbo.build/schema.json",
        tasks: {
          build: {
            dependsOn: ["^build"],
            outputs: ["dist/**"],
          },
          dev: {
            cache: false,
            persistent: true,
          },
          typecheck: {
            dependsOn: ["^typecheck"],
            outputs: [],
          },
          lint: {
            dependsOn: ["^lint"],
            outputs: [],
          },
          test: {
            dependsOn: ["^test"],
            outputs: [],
          },
        },
      });
    },
  },

  "typescript-starter": {
    apply: (blueprint, model) => {
      const biomeEnabled = !blueprint.policySelections.disabledShoulds.includes(
        "biome",
      );

      const lintCommand = biomeEnabled
        ? "bunx @biomejs/biome check ."
        : 'echo "Biome not enabled"';

      addDevDependency(model, "typescript");
      addDevDependency(model, "@types/node");

      writeJson(model, "apps/api/package.json", {
        name: "@workspace/api",
        private: true,
        type: "module",
        scripts: {
          dev: "bun --watch src/index.ts",
          build: "bun build src/index.ts --outdir dist",
          typecheck: "tsc --noEmit",
          lint: lintCommand,
          test: 'echo "No tests configured yet"',
        },
        dependencies: {
          "@workspace/shared": "workspace:*",
        },
        devDependencies: {},
      });

      writeJson(model, "apps/api/tsconfig.json", {
        extends: "../../tsconfig.base.json",
        include: ["src/**/*.ts"],
      });

      writeText(
        model,
        "apps/api/src/index.ts",
        `import { createServer } from "node:http";
import { greet } from "@workspace/shared";

const port = Number(process.env.PORT ?? 3000);

const server = createServer((req, res) => {
  if (req.url === "/health") {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: true }));
    return;
  }

  res.writeHead(200, { "content-type": "application/json" });
  res.end(JSON.stringify({ message: greet("world") }));
});

server.listen(port, () => {
  console.log(\`API listening on http://localhost:\${port}\`);
});
`,
      );

      writeJson(model, "packages/shared/package.json", {
        name: "@workspace/shared",
        private: true,
        type: "module",
        exports: {
          ".": "./src/index.ts",
        },
        scripts: {
          build: "bun build src/index.ts --outdir dist",
          typecheck: "tsc --noEmit",
          lint: lintCommand,
          test: 'echo "No tests configured yet"',
        },
        dependencies: {},
        devDependencies: {},
      });

      writeJson(model, "packages/shared/tsconfig.json", {
        extends: "../../tsconfig.base.json",
        include: ["src/**/*.ts"],
      });

      writeText(
        model,
        "packages/shared/src/index.ts",
        `export function greet(name: string): string {
  return \`hello, \${name}\`;
}
`,
      );
    },
  },

  biome: {
    apply: (_blueprint, model) => {
      addDevDependency(model, "@biomejs/biome");

      writeJson(model, "biome.json", {
        formatter: {
          enabled: true,
          indentStyle: "space",
        },
        linter: {
          enabled: true,
          rules: {
            recommended: true,
          },
        },
        javascript: {
          formatter: {
            quoteStyle: "double",
            semicolons: "always",
          },
        },
      });
    },
  },
};

export function applyResolvedCapabilities(
  blueprint: Blueprint,
  resolvedCapabilities: Capability[],
  model: RepoModel,
): void {
  for (const capability of resolvedCapabilities) {
    const definition = capabilityRegistry[capability];
    const implementation = moduleImplementations[capability];

    if (!definition) {
      throw new Error(`Missing capability definition: ${capability}`);
    }

    if (!implementation) {
      throw new Error(`Missing module implementation: ${capability}`);
    }

    implementation.apply(blueprint, model);
  }
}